web_shop/web_shop/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

web_shop/web_shop/cupons/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^apply/$', views.CuponApply, name='apply')
]

web_shop/web_shop/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.AdminOrderDetail, name='AdminOrderDetail'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.AdminOrderPDF, name='AdminOrderPDF')
]

web_shop/web_shop/shop/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^(?P<category_slug>[-\w]+)/&', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/&', views.ProductDetail, name='ProductDetail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_shop/web_shop/web_shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cupons/', include('cupons.urls', namespace='cupons')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^admin/category/', include('countstat.urls', namespace='countstat')),
    url(r'^', include('shop.urls', namespace='shop'))
]

web_shop/web_shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

web_shop/web_shop/cart/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Profuct as Product
from .cart import Cart
from .forms import CartAddProductForm
from cupons.forms import CuponApplyForm

@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:CartDetail')

def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')

def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'update': True })
    cupon_apply_from = CuponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart,
                                                'cupon_apply_from':cupon_apply_from})

web_shop/web_shop/cart/templates/cart/detail.html
{% extends 'shop/base.html' %}

{% block title %}
	Your basket of products
{% endblock %}

{% block content %}
	<h1>Your basket of products</h1>
	<table class="table-cart" border="1px">
		<thead>
			<tr>
				<th>Picture</th>
				<th>Product</th>
				<th>Quantity</th>
				<th>Delete</th>
				<th>Price</th>
				<th>Full price</th>
			</tr>
		</thead>
		<tbody>
			{% for item in cart %}
				{% with product=item.product %}
					<tr>
						<td class="cart-img">
							<a href="{{ product.get_absolute_url }}">
								<img src="{{ product.image.url }}" class="img-resposive">
							</a>
						</td>
						<td>{{ product.name }}</td>
						<td>
							<form action='{% url "cart:CartAdd" product.id %}' method="post" class="add">
								{{ item.update_quantity_form.quantity }}
								{{ item.update_quantity_form.update }}
								{% csrf_token %}
								<input type="submit" value="Update">
							</form>
						</td>
						<td><a href='{% url "cart:CartRemove" product.id %}'></a></td>
						<td class="num">{{ item.price }} $</td>
						<td class="num">{{ item.total_price }} $</td>
					</tr>
				{% endwith %}
			{% endfor %}
			{% if cart.cupon %}
				<tr class="subtotal">
					<td colspan="4"></td>
					<td>{{ cart.get_total_price }}</td>
				</tr>
				<tr>
					<td>
						"{{ cart.cupon.code }}" cupon on ({{ cart.cupon.discount }} % less)
					</td>
					<td colspan="4"></td>
					<td class="num discount">- {{ cart.get_discount|floatformat:"2" }} $</td>
				</tr>
			{% endif %}
			<tr class="total">
				<td>Total</td>
				<td colspan="4"></td>
				<td class="num">{{ cart.get_total_price_after_discount|floatformat:"2" }} $</td>
			</tr>
		</tbody>
	</table>
	<p>Use cupon</p>
	<form action='{% url "cupons:apply" %}' method="post" class="add">
		{% csrf_token %}
		{{ cupon_apply_form }}
		<input type="submit" value="Update">
	</form>
	<p class="text-right">
		<a></a>
		<a href='{% url "shop:ProductList" %}' class="btn btn-light">Shop more</a>
		<a href='{% url "orders:OrderCreate" %}' class="btn">Checkout</a>
	</p>
{% endblock %}