web_shop/web_shop/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

web_shop/web_shop/shop/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^(?P<category_slug>[-\w]+)/&', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/&', views.ProductDetail, name='ProductDetail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_shop/web_shop/web_shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cupons/', include('cupons.urls', namespace='cupons')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^admin/category/', include('countstat.urls', namespace='countstat')),
    url(r'^', include('shop.urls', namespace='shop'))
]

web_shop/web_shop/shop/models.py
from django.db import models

# Create your models here.

from django.core.urlresolvers import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductListByCategory', args=[self.slug])

class Profuct(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name='Category')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Title')
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, verbose_name='Product picture')
    description = models.TextField(blank=True, verbose_name='Description')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Price')
    stock = models.PositiveIntegerField(verbose_name='In of stock')
    available = models.BooleanField(default=True, verbose_name='Available')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductDetail', args=[self.id, self.slug])
        
    

web_shop/web_shop/shop/views.py
from django.shortcuts import render

# Create your views here.

from .models import Category, Profuct as Product
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from django.contrib import messages
from django.contrib.messages import get_messages

def ProductList(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    messages.add_message(request, messages.INFO, 'You were return on the main paige')
    storage = get_messages(request)
    return render(request, 'shop/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products,
        'storage': storage
    })

def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

web_shop/web_shop/shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
	
	<link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'>
	<link rel="stylesheet" href='{% static "css/style.css" %}'>	
</head>
<body>
	<section id="header">
		<div class="top container">	
			<h1>The Online Shop
			<a href='{% url "shop:ProductList" %}' class="btn btn-light">Home</a></h1>
			{% if storage %}
				<ul class="messages">
					{% for message in storage %}
						<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					{% endfor %}
				</ul>
			{% endif %}
		</div>
		<div class="top-bl">
			<div class="top container">
				<div class="cart">
					{% with total_items=cart|length %}
						{% if cart|length > 0 %}
							Your basket:
							<a href='{% url "cart:CartDetail" %}'>
								{{ total_items }} prod. {{ cart.get_total_price }} $
							</a>
						{% else %}
							Your basket is empty
						{% endif %}
					{% endwith %}
				</div>
			</div>
		</div>
	</section>
	<section id="content row" class="container">
		{% block content %}{% endblock %}
	</section>
</body>
</html>